### ISSUE TITLE
Variantie Laplace distributie

### ISSUE THREAD

**Issue by arthur-arthur** [JanAlexanderPersonal/Prinstat_HW3#10]
De shift die gebruikt werd voor de Laplace distributie was (2*pi^2) /6, volgens de formule zou dit (pi^2) / 6 moeten zijn (s = 1), denk ik? Ik heb dit aangepast in de code maar de simulatie die ik vannacht heb gelopen heeft nog wel de vorige variantie gebruikt.
Als dit inderdaad een foutje is kan ik ze vannacht nog wel eens laten lopen, maar dat gaat weinig effect hebben op de algemene conclusie dus dan kunnen we daar alvast mee verder.

**Comment by JanAlexanderPersonal** [comment]
Voor de logistische distribution?

die 2/6 komt van de binomiale coefficient. Ik denk dat die 2/6 wel juist is. maar goed. Dat komt ook maar van wikipedia...

**Comment by arthur-arthur** [comment]
Inderdaad, logistische. Ik was verkeerd, ik had over die 2 gekeken omdat die al in de exponent stond, excuses!
