### ISSUE TITLE
Join two code branches in the repo

### ISSUE THREAD

**Issue by JanAlexanderPersonal** [JanAlexanderPersonal/Prinstat_HW3#4]
In the last push to the master, the R-code file was renamed outside the git. the new .R file should be a new version of the other.

This can lead to confusion.

**Comment by arthur-arthur** [comment]
Excuses, beginnersfoutje. Om zeker te zijn dat ik het begrijp: ik heb de laatste aanpassing (rlaplace) op HW3.R gedaan (de versie met de t.test die ik inderdaad per vergissing hernoemd heb), moeten we nu gewoon de originele HW3_G15_JAL.R verwijderen? Of zijn daar nog aanpassingen aan gedaan sinds dinsdag?

**Comment by JanAlexanderPersonal** [comment]
Geen probleem. HW3_G15_JAL is niet meer veranderd. Die kan dus inderdaad inderdaad gewoon weg. Het feit dat we dan de eigenlijke versiegeschiedenis kwijt zijn maakt nu niet uit.

In principe zou je eigenlijk moeten zorgen dat het duidelijk blijft dat HW3.R eigenlijk een nieuwe commit is van HW3_G15_JAL. Om dat te doen kan je:

- [ ] git pull the repo

- [ ] remove HW3_G15_JAL.R 

- [ ] Rename HW3.R to HW3_G15_JAL.R --> want het is eigenlijk de nieuwe versie van dit document

- [ ] Add everything and commit + push --> nu weet git weer dat er een nieuwe versie is van de R code

- [ ] Rename the new version of HW3_G15_JAL.R to HW3.R - INSIDE GIT (met edit this file)

**Comment by arthur-arthur** [comment]
Ok, bedankt voor de uitleg, helemaal mee!
