### ISSUE TITLE
Uniform distributie eruit of delta ifv variantie

### ISSUE THREAD

**Issue by arthur-arthur** [JanAlexanderPersonal/Prinstat_HW3#9]
In de simulaties die ik heb gedaan is de power = 1 voor de uniform distributie, wat uiteraard weinig zinvol is. Volgens mij is dit omdat we de delta niet ifv de variantie van de distributie kiezen (zoals in de cursus). Ik stel voor die distributie niet te includeren, ofwel een delta te kiezen in functie van de variantie zodat alle testen een power geven groter dan 0 en kleiner dan 1.

**Comment by JanAlexanderPersonal** [comment]
Ik zou dan voor een delta afhankelijk van de variantie gaan. Kan jij dat in de code toevoegen?

**Comment by arthur-arthur** [comment]
Aangepast met delta = sd(Y1) / 2
Ik heb de compute.power functie binnenin de simulatie loop gezet omdat de delta telkens moet worden gekozen na random sampling van Y1.

**Comment by JanAlexanderPersonal** [comment]
Ik twijfel nu even: Ik vind het niet logisch dat we voor elk sample een andere delta nemen. Wat denk je van het volgende: we kennen de variantie van de distributies waaruit we samplen. Voor de uniforme distributie is dit var(X) = (b-a)²/12. Zouden we dan niet een vaste delta moeten nemen op basis hiervan?
Hetzelfde zouden we kunnen doen voor de andere verdelingen. Ik heb wel eens gekeken en die zijn niet allemaal op 1-2-3 te vinden. Desnoods kan ik ook met R 1 keer een sample nemen van 10^6 elementen uit elke verdelen en de variantie op basis daarvan schatten.

Wat denken jullie?

**Comment by arthur-arthur** [comment]
Ik redeneer eigenlijk omgekeerd: dat die simulatie net moet toelaten een idee te hebben van de eigenschappen van de test in 'real life', maw wanneer de mean, median, variantie,... van de samples onderhevig zijn aan willekeur (ttz niet altijd precies de populatie mean, median, variantie representeren). 
Ik vraag mij af of het resultaat niet hetzelfde zou zijn. Nu nam ik sqrt(Var(X))/2, waarbij sd(X) de sample variantie is (met n-1 in de noemer). In principe zou die dus een unbiased estimator moeten zijn van sqrt(Var(X)), zodat de expected value van 1000 schattingen sd(X)^2 de populatie Var(X) zou moeten zijn, niet?

**Comment by JanAlexanderPersonal** [comment]
De statistieken van de samples zijn inderdaad onderhevig aan willekeur: het gemiddelde en de sd van een sample zal altijd wat anders zijn. Maar de populatie waaruit je dat sample neemt moet toch altijd dezelfde blijven. Nu ga je eigenlijk altijd uit een andere populatie 2 samplen, toch?

**Comment by arthur-arthur** [comment]
Nee die is altijd hetzelfde, de characteristics van de populatie zijn gedefinieerd in de functie argumenten (niet expliciet in ons geval, maar die hebben altijd een default), bvb:
rnorm(n, mean = 0, sd = 1) en rexp(n, rate = 1),...

**Comment by JanAlexanderPersonal** [comment]
Onze populatie Y2 wordt toch bepaald door de som van 
1 - de R-populatie waaruit we samplen
2 - de factor die we erbij tellen

we zouden dus net zo goed kunnen schrijven
Y2 <- rnorm(n, mean=delta * var/2, sd =1)
als
Y2 <- rnorm(n, mean=0, sd =1) + delta * var/2

Waar ga ik de mist in?

**Comment by arthur-arthur** [comment]
Nergens volgens mij. :) Je hebt inderdaad gelijk, die populaties zijn strikt genomen niet identiek, maar die delta zorgt enkel voor een locatieshift van de mean, en dat heeft geen effect op de variantie. Die 2 expressies zouden dus inderdaad net hetzelfde moeten geven.

**Comment by JanAlexanderPersonal** [comment]
ok, 
Ik heb dan maar die vaste shift aangemaakt.
Dat is handigen om beter te onderzoeken hoe N het resultaat beïnvloed.
N = 200 lijkt toch het minimum te zijn.
Ik laat die uitgebreide simulatie straks nog eens lopen.
